### ISSUE TITLE
多部手机无法选择投屏的手机

### ISSUE THREAD

**Issue by gavincwb** [ystianxie/DScrcpy#1]
投屏正常 但是在多部手机连接的时候无法选择设备。 设备里显示其他手机，但是点开的时候选择出现禁止标志。

**Comment by ystianxie** [comment]
检查设备是否是“device” 状态，状态不对，会出现，但是无法选择

**Comment by gavincwb** [comment]
> 检查设备是否是“device” 状态，状态不对，会出现，但是无法选择

<html>
<body>


03:52:07 | List of devices attached
-- | --
03:52:07 | 2d7534f2 device
03:52:07 | ZD222BHQXQ device
03:52:07 | ed6f63ef device


</body>
</html>

**Comment by ystianxie** [comment]
Windows下命令行结果不可见字符导致，已更新，明天开始修复其他问题
